# Generated by Django 4.2.1 on 2023-05-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=16, unique=True)),
                ('management_ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TapePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tapeman.library')),
            ],
        ),
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=16)),
                ('capacity', models.FloatField(max_length=8)),
                ('full', models.BooleanField()),
                ('data_expiration', models.DateField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapeman.tapepool')),
            ],
        ),
    ]
